#### 协程错误处理

1. 错误原因：多个协程工作，其中一个协程出现panic，都会导致程序崩溃
2. 解决方法：利用defer + recover错误处理机制捕获panic进行处理，即使协程出现问题，主线程仍然不受影响可以继续执行。

```go
package main

import (
	"fmt"
	"sync"
)

var wg sync.WaitGroup

func main() {
	wg.Add(2)
	// 开启一个打印 1-10 证书的协程
	go func() {
		defer wg.Done()
		for i := 1; i < 11; i++ {
			fmt.Println("print:", i)
		}
	}()

	// 开启一个被除数为0的错误协程
	go func() {
		defer wg.Done()

		defer func() {
			err := recover()

			if err != nil {
				fmt.Println("除法协程出错了", err)
			}
		}()
		num1 := 10
		num2 := 0

		res := num1 / num2
		fmt.Println(res)
	}()

	wg.Wait()
}

```

