### 错误处理

与js不同，go中不再使用try ... catch 捕获错误，而是使用defer + recover。示例如下:

```go
package main

import (
	"fmt"
)

func main() {
	fmt.Println("fail()执行前")
	fail()
	fmt.Println("fail() 执行后")
}

func fail() {
	defer func() {
		// 调用recover内置函数，可以捕获错误；
		err := recover()

		// 如果没有捕获错误，返回值为零值：nil，如果不为nil，则说明有错误
		if err != nil {
			fmt.Println("错误已经捕获")
			fmt.Println("错误是：", err)
		}
	}()
	num1 := 10
	num2 := 0
	res := num1 / num2
	fmt.Println(res)
}

```

