#### 自定义错误

需要引用内置的 errors包

1. errors.New(string) (error): 使用字符串创建一个错误

```go
package main

import (
	"errors"
	"fmt"
)

func main() {
	fmt.Println("fail()执行前")
	err := fail()
    // 自定义错误后也不影响程序正常运行
	if err != nil {
		fmt.Println(err)
        // 如果要终止错误，则需调用内置函数panic
        panic(err)
	}
	fmt.Println("fail() 执行后")
}

// 定义返回值类型为 error 若无错误返回 nil
func fail() error {
	num1 := 10
	num2 := 0
	if num2 == 0 {
		err := errors.New("error:除数不能为0")
		return err
	} else {
		res := num1 / num2
		fmt.Println(res)
		return nil
	}

}

```

